name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code from the master branch
    - uses: actions/checkout@v3.5.3

    # Sets up .NET Core SDK 7.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.0
    
    # Publishes the Blazor project to a release folder
    - name: Publish .NET Core Project
      run: dotnet publish LinfoPersonalPage/LinfoPersonalPage.csproj -c Release -o release --nologo

    # Changes the base-tag in index.html from "/" to match repo subdirectory
    - name: Change base-tag in index.html from / to Whatever Your Project Is Called
      run: sed -i 's/<base href="\/" \/>/<base href="\/LinfoPersonalPage\/" \/>/g' release/wwwroot/index.html

    # Copy index.html to 404.html to account for missing file
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    
    - name: Deploy GitHub Pages site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot

# Based heavily on https://github.com/Swimburger/BlazorGitHubPagesDemo/blob/master/.github/workflows/main.yml, with some alterations
